idf_component_register(SRCS
    "main.c"
    "settings/display/display_init.c"
    "settings/touch/touch.c"
    "settings/wifi/wifi_ap.c"
    "settings/wifi/tcp_server.c"
    "settings/time/rtc_time.c"
    "settings/time/time_from_build.c"
    "GUI/wallpaper/wallpaper800400.c"
    "GUI/fonts/my_arial.c"
    "GUI/ui/ui.c"
    INCLUDE_DIRS 
        "."
        "settings/display"
        "settings/touch"
        "settings/wifi"
        "settings/time"
        "GUI/wallpaper"
        "GUI/fonts"
        "GUI/ui"
    REQUIRES nvs_flash esp_wifi
)